### ISSUE TITLE
기능 분배

### ISSUE THREAD

**Issue by Sunmyunghan** [Sunmyunghan/Folking-workflow#1]
- [x] 팀원 명단 작성하기
- [x] 팀원 Github 아이디 적기
- [x] 추가 내용 고민하기

**Comment by bcyoo** [comment]
다들 여기까지 보고 계신건가요??

**Comment by y-moon20** [comment]
네 근데 fizzbuzz 이슈랑 역할분배이슈는 따로 없어서 기다리는 중이었어요.

**Comment by Sunmyunghan** [comment]
다른 이슈 작성중이라 늦게 봤습니다.
다른 추가 내용있으면 여기서 이야기 해주세요!

**Comment by y-moon20** [comment]
fizzbuzz랑 introduce어떻게 분배하면 될까요

**Comment by Sunmyunghan** [comment]
저희 한 분이 아직 안오셔서 제가 슬랙으로 그분에게 url 다시 보내드릴게요!

**Comment by y-moon20** [comment]
다예님 이모지 누른거 보면 여기 계시는데 멘션을 안쓰셔서 participants에 안뜨는 것 같습니다

**Comment by dayebbi** [comment]
아 네네 ㅎㅎ 눈팅하고있었어요

**Comment by dayebbi** [comment]
멘션 작성해야 participants에 리스트가 들어가는건가봐요..
제가 따로 수락해야하는 절차가 있나요?

**Comment by bcyoo** [comment]
하고싶은거 정하시고 잇슈 적으시공 클론 하시면 될거같아요~

**Comment by dayebbi** [comment]
참여자 리스트에 추가 됐네요~ 제가 fizzbuzz 해도 될까요?

**Comment by Sunmyunghan** [comment]
issue는 이대로 괜찮은가요? 혹시 추가해야 할 것 없을까요?

**Comment by y-moon20** [comment]
일단 이슈는 두개로 괜찮을것같습니다!

**Comment by bcyoo** [comment]
이슈 두개 괜찮은것 같아요

**Comment by bcyoo** [comment]
다예님이 fizzbuzz하시고
저랑 영주님이랑

각자 본인거 그리고 한명 추가해서 md파일 만들면 되지않을가요??

**Comment by bcyoo** [comment]
유병철 x .md
문영주 x .md  해서 마지막에 내용합치기..?

**Comment by Sunmyunghan** [comment]
진행하시면서 생기는 이슈는 올려주시면 제가 확인하고 있겠습니다.

**Comment by y-moon20** [comment]
네 다예님 fizzbuzz 혼자하는거 괜찮으세요?
다예님 fizzbuzz 괜찮으시면, 병철님하고 저하고 introduce를 두명씩 맡아서 하고
다에님 fizzbuzz 누군가와 함께하고 싶으시면 introduce를 한명이 하면 될 것 같습니다. :)

**Comment by bcyoo** [comment]
다예님~ 혼자하시는거 괜찮으신가요~?

**Comment by bcyoo** [comment]
하고계시네요 ㅋㅋ 그러면 이거 나눠서하시죠

**Comment by y-moon20** [comment]
네 병철님이 해서 올려주시면 제가 그거 당겨받아서 마크다운 정리하면서 마저 작성할게요!
편하신분으로 두분 작성해주세요!

**Comment by bcyoo** [comment]
넵넵  먼저진행가겠습니다

**Comment by y-moon20** [comment]
명한님 이 이슈 수정가능하다면 "기능분배" 요런 제목이랑 내용으로 바꾸는 것이 괜찮을 것 같아요.
그리고 여기의 내용은 #3에 병철님이 만드신 이슈로 이동 가능할까요?

**Comment by Sunmyunghan** [comment]
네 한번 해보겠습니다!

[edit]

완료했습니다!
