### ISSUE TITLE
Make fizzbuzz.py

### ISSUE THREAD

**Issue by Sunmyunghan** [Sunmyunghan/Folking-workflow#2]
- [x] fizz 코드 작성
- [x] buzz 코드 작성
- [x] fizzbuzz 코드 작성

**Comment by dayebbi** [comment]
fizzbuzz 제가 진행하겠습니다. assignee 지정 부탁드립니다.

**Comment by dayebbi** [comment]
> * [x]  fizz 코드 작성
> * [x]  buzz 코드 작성
> * [x]  fizzbuzz 코드 작성

**Comment by Sunmyunghan** [comment]
지정 완료했습니다! 잘 부탁드리겠습니다.

**Comment by Sunmyunghan** [comment]
Close #2
