### ISSUE TITLE
introduce team

### ISSUE THREAD

**Issue by bcyoo** [Sunmyunghan/Folking-workflow#3]
- [x] 팀원 명단 작성

- [x] 팀원 소개 작성

**Comment by y-moon20** [comment]
병철님 소개 1차작성끝나면 여기에 멘션해주세요 :)

**Comment by bcyoo** [comment]
네

**Comment by bcyoo** [comment]
푸쉬했어요 ㅜ 너무늦었네요..

**Comment by y-moon20** [comment]
작성하신거 아마 풀리퀘 올리셔서 승인 받으셔야 저한테 보일것같아요!

**Comment by bcyoo** [comment]
보이시나요??

**Comment by bcyoo** [comment]
resolve를 해야하나 안해야하나 고민하다가 마지막에 해야할 것같아서 이름만 남겼어요..
맞나요..?

**Comment by y-moon20** [comment]
앗 resolve #3 하시기 편하라고 일부러 이슈4 생성하긴했는데,
그냥 이대로 해도 괜찮을 것 같아요!

**Comment by Sunmyunghan** [comment]
merge까지 완료했습니다!
