### ISSUE TITLE
introduce team part2

### ISSUE THREAD

**Issue by y-moon20** [Sunmyunghan/Folking-workflow#4]
- [x] : 병철님 작업분 확인
- [x] : 나머지 두 분 작성
- [x] : 마크다운 양식 맞추기
- [x] : 풀리퀘 올리기
- [x] : 요청받은 것 수정하기

**Comment by Sunmyunghan** [comment]
유병철 팀원님이 올리신 파일 merge 완료했습니다.

**Comment by y-moon20** [comment]
upstream에서 pull해오는 과정에서 문제가 있어서 시작이 늦었습니다.
지금 introduce.md작업 시작합니다.
